sudo: required

language: generic

env:
  - SELENIUM_BROWSER=chrome
  - SELENIUM_BROWSER=firefox

services:
  - docker

before_script:
  - cd tests
  - docker-compose run --rm node npm run build
  - docker-compose up -d $SELENIUM_BROWSER

script:
  - docker-compose ps
  # exclude optional tests
  - docker-compose run --rm codeceptjs codeceptjs run-multiple basic:$SELENIUM_BROWSER --invert --grep  '@optional'

after_script:
  # run optional tests
  - docker-compose run --rm codeceptjs codeceptjs run-multiple basic:$SELENIUM_BROWSER --grep '@optional'
